# CONTIKI_PROJECT doit être définit comme
# le nom de votre projet
CONTIKI_PROJECT = my_hello_world



# Les lignes suivantes sont toujours les même
# les projets Contiki
all: $(CONTIKI_PROJECT)

CONTIKI = ../.. # Chemin vers le dossier root des sources contiki-ng
include $(CONTIKI)/Makefile.include
